build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.1
            project_setup:
                override: true
            tests:
                override:
                - php-scrutinizer-run

filter:
    excluded_paths:
    - docs
